version: "3.9"
services:
    postgres:
      image: postgres:10.5
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5
    postgres-pgadmin:
      image: dpage/pgadmin4:6.11
      restart: always
      volumes:
        - ./pgadmin-data:/var/lib/pgadmin
      ports:
        - '5433:80'
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=postgres
    test:
      image: "lab-4"
      volumes:
        - .:/app
      command: python3 -m pytest
    run:
      image: "lab-4"
      depends_on:
        postgres:
          condition: service_healthy
      volumes:
        - .:/app
      command: python3 main.py
